version: '3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9000:9090"
    volumes:
      - ${PWD}/telemetry/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector
    command: ["--config=/root/otel-collector/config.yml"]
    volumes:
      - ${PWD}/telemetry/otel-collector:/root/otel-collector/
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "55681:55681"
      - "13133:13133"  # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "4319:4319"   # OTLP http receiver

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "0"
    ports:
      - 3001:3000
    restart: unless-stopped
    volumes:
      - ${PWD}/telemetry/grafana/:/etc/grafana/provisioning/
      - ${PWD}/telemetry/grafana/:/var/lib/grafana/dashboards/
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data:
